<?php

/**
 * @file
 * Defines menu items for the Eventbrite API module.
 */

/**
 * Implements hook_menu().
 */ 
function eventbrite_api_menu() {
  $items = array();
	$items['admin/eventbrite'] = array(
    'title' => 'Eventbrite',
    'description' => 'Administer Eventbrite.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );
  $items['admin/eventbrite/config'] = array(
    'title' => 'Eventbrite configuration',
    'description' => 'Configure the Eventbrite API module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_eventbrite_api_admin'),
    'access arguments' => array('administer eventbrite_api config'),
    'file path' => drupal_get_path('module', 'eventbrite_api') . '/includes',
    'file' => 'forms.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
